language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t tititity/se234-lab11-frontend .
- docker push tititity/se234-lab11-frontend
service: docker
env:
  global:
  - secure: F4+K4EueciWbUzIEzMDIAyxMYpY5QP+cI0faKIviZ/Fq+/Z09pCzDRVqUneEmengvb2x8GPqZ3QY4sdmglrvC3pDzI1tVTu98zDpagjqVClKge7yWlAJRYFre9KV3gdIbYyXeYbjVOmx9RGUJPuhdTLfcTF1kZf6pfOTuyZWt2wEvfPYhKWNP1WRlIlLxtQJIhm4V8g18SEsF3blcgAK+pILz1S39q6BVd5fWd7Ik7MxWgQ0ZINifv90TKmUepy8QvSTb6UEwElOhHoxelFtFjw/lXwpHFSbliNmw8pK7Zp2hom2d/7aSIg2c1XzruDWMMsCNMjlc5u3BjsdMWsAk1iC7XS0Bmq1DgrcDUnAh1SeQhIKiqX0rrc0aSHvULmqWorceR3SoKrmOZVrPmtCBY8K4hlealP0QWfOFXYEyPJl+bq+rpc0f2NK0eOmgB3ex+7MEccTT7spSHNEsXGiESZJQy2duk+QgSGNB+4JZ/fhcdOE7perNnGvnz63SWdmP5Pnm/3yvQ+e76knHaOe9FD9qlsCoIy/YbiYr9v2nd/L7N/vCjDE1P3xDOjx+AuglgHxxKBu4hiVUuCF1wD0nMfAZxaODjJSNOfLJSb6dEacKVFqJJJ2Ncj7z8jqZyALCgorcn473O8jOoE6ApvY8e2J6pY4e4vU3xyV7OJ1Y2I=
  - secure: uRUy6kAFBcwD853IP3YSN88zkf6eVFvMic1Buqxcy8RwShV47AR0Dci913ygwGGtiHTnCdF6IHj5MvsFGEZNWZ3cU2YzRZPWOY+QrokrD43sQ0H0k5Zhcr29+MTk192dudHghWNzZKzE37fHmTan1Fxf3hKaX3jbFjQU1+3VJi4MXvMAzbP7QvRictGJ8Zx3Z8CpoWImBg0YKhtYtTJ+o7ssBc0wl7N/LjyzWpdMaPQSqEUa4hJNhk5jOJ1YTIF+LuZtAADMGjc/lEonQBmqJwAVh9xMKdX500Zm3MjcwLhD9MWElR04iWC83OrWFG2pQd91f1zo1gVKZ258wBOSa2UHFG9jm1Dinkd90BnZef4vVxR1GKBMuruZxwHXobFygIGpHv5gZ3FjjTW32/4MOpVCSsDrEkfKoMRXhB031jnG4Rwdnrsu4yKFhvwTWnwxRk7GBBcCXf4HGYsl4if2PDk/MBQ9VYTMBjF4UyJUlMfuV6axySiZPs9VGwtYfg17ZfVUjbJAfdTghUFLIGarqTFg/BvjFEazr6V6xm9OJBXEiQ+2rY+ZqNPSYFeso0U3cWnhw5LsPU7gTbnP0GM98pWSAs7ulmr6ehWvLITWrD1LxleTIrJC3Nkh65h8uipfaJJj3f/06df+WCKDolFZo2hBHIK4pcHrY3vkYxKlTAs=
